version: 2
updates:
  # Golang dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      exclude:
        - "github.com/getoutreach/*"
    # stencil-golang managed dependencies
    ignore:
      - dependency-name: github.com/getoutreach/gobox
      - dependency-name: github.com/getoutreach/stencil-golang/pkg
      - dependency-name: github.com/urfave/cli/v3
      - dependency-name: github.com/getoutreach/mint
      - dependency-name: github.com/getoutreach/governancelib
      - dependency-name: github.com/getoutreach/datastores/v2
      - dependency-name: github.com/getoutreach/httpx
      - dependency-name: github.com/getoutreach/governance
      - dependency-name: github.com/getoutreach/services
      ## <<Stencil::Block(dependabotGoIgnore)>>

      ## <</Stencil::Block>>

  # Ignore semantic-release, this code is only executed in CI.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      exclude:
        - "@getoutreach/*"
    ignore:
      - dependency-name: "*"

  ## <<Stencil::Block(dependabotPackageManagers)>>

  ## <</Stencil::Block>>
