[task_config]
includes = [".bootstrap/.mise/tasks", ".mise/tasks"]

[env]
## <<Stencil::Block(customMiseEnvironment)>>

## <</Stencil::Block>>

[hooks]
enter = ["$MISE_PROJECT_ROOT/scripts/devbase.sh"]

## <<Stencil::Block(customMiseHooks)>>

## <</Stencil::Block>>

[tools]
"npm:prettier" = "2"

## <<Stencil::Block(customMiseTools)>>

## <</Stencil::Block>>

## <<Stencil::Block(extraMise)>>

## <</Stencil::Block>>
