name: CI
on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.16-alpine
    steps:
      - name: Download OS Dependencies
        run: apk add --no-cache git make bash curl tar gcc libc-dev sudo
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Go Dependencies
        uses: actions/cache@v2
        id: go-dep-cache
        with:
          path: /home/worker/go/pkg
          key: v1-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            v1-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            v1-${{ runner.os }}-go-
      - name: Download Dependencies
        run: make dep
      - name: Run Tests
        run: make test
